Bindings refactoring & Automap bindings
odamex/odamex pull request #167
Opened 2020-05-10 01:34 UTC by Ch0wW

Refactored the bindings, so that all new binding commands won't need to be copy/pasted.
Also added independant automap bindings, and added a menu control dedicated to it.

2020-05-13 02:53 UTC, AlexMax commented
Nice work.  My only concern is that if you upgrade from an older version of Odamex and have an existing config, none of the automap keys will be bound by default.

2020-11-07 21:06 UTC, Ch0wW commented
The last commit should rectify the issue you mentionned.

2020-11-07 23:12 UTC, AlexMax requested changes
Mostly looks good, just have a few small things to take care of and I'll merge ASAP.

2020-11-07 23:12 UTC, AlexMax commented on client/src/c_bind.cpp
> +END_COMMAND(unbind)
Could you add a short little help if argc < 2 instead of printing nothing?

2020-11-07 23:12 UTC, AlexMax commented on client/src/c_bind.cpp
> +END_COMMAND(undoublebind)
Could you add a short little help if argc < 2 instead of printing nothing?

2020-11-07 23:12 UTC, AlexMax commented on client/src/c_bind.cpp
> +END_COMMAND(amunbind)
Could you add a short little help if argc < 2 instead of printing nothing?

2020-11-08 00:26 UTC, AlexMax approved these changes

2020-11-08 00:27 UTC, merged

2020-11-08 00:27 UTC, AlexMax commented
LGTM