Enable vileghosts behavior by default
odamex/odamex pull request #326
Opened 2021-04-28 20:56 UTC by DCGRetrowave

This change enables the vanilla engine's Arch-vile ghost monster resurrect quirk by default on Odamex, allowing this behavior for both single player and multiplayer games.  "co_vileghosts" can be set to "1" to disable this as Boom compatibility fixes the bug.  Several vanilla/limit-removing maps abuse this bug as a feature so this will allow those maps to run as intended (and it's always fun to witness this obscure glitch occur in maps where there is no intentional ghost trap).

2021-04-28 21:44 UTC, fuzztooth requested changes

2021-04-28 21:44 UTC, fuzztooth commented on common/c_cvarlist.cpp
> +	CVAR(			co_vileghosts, "0", "Disables vanilla's ghost monster quirk that lets Arch-viles resurrect crushed monsters as unshootable ghosts",
This should be called co_novileghosts since setting this to 1 _disables_ thereby changing vanilla behavior.

2021-05-15 19:05 UTC, AlexMax commented
Something has gone incredibly wrong with your most recent commit.  You seem to have accidentally deleted a good number of files from your repository.

In the interest of getting your changes in, I am going to see if I can construct a PR from you commits.

2021-05-15 20:25 UTC, AlexMax commented
Replaced with #359

2021-05-15 20:25 UTC, closed without merging