Fix several MAPINFO tokens
odamex/odamex pull request #362
Opened 2021-05-16 00:36 UTC by Ch0wW

This PR fixes many problems reported from issue #358 .

It currently does the following:
- Creates `compat_nopassover` flag.
- Fix "SKY1/SKY2" "scrollspeed" argument being truly optional.
- Fix the "key" and "episode" tokens not being properly parsed.
- Create a fallback for the name if the "lookup" doesn't work.

2021-05-16 03:59 UTC, AlexMax requested changes
Just some `const` changes.

2021-05-16 03:59 UTC, AlexMax commented on common/g_level.cpp
> +const bool P_AllowDropOff()
You shouldn't return a `const` value type - the `const` is useless.

2021-05-16 03:59 UTC, AlexMax commented on common/g_level.cpp
> +const bool P_AllowPassover()
You shouldn't return a `const` value type - the `const` is useless.

2021-05-16 03:59 UTC, AlexMax commented on common/g_level.cpp
> +    VERSION_CONTROL (g_level_cpp, "$Id$")
Weird spacing here?

2021-05-16 03:59 UTC, AlexMax commented on common/sc_man.cpp
> +const bool SC_CheckFloat()
You shouldn't return a `const` value type - the `const` is useless.

2021-05-16 12:01 UTC, Ch0wW commented
Latest commit should take care of these small errors.

2021-05-17 13:44 UTC, AlexMax approved these changes
LGTM

2021-05-17 13:44 UTC, merged