fix bug 518
odamex/odamex pull request #523
Opened 2022-01-24 10:08 UTC by DeathEgg

2022-01-24 18:42 UTC, rakohus commented
Tested and confirmed to be working. Just needs code review

2022-01-25 02:59 UTC, AlexMax requested changes

2022-01-25 02:59 UTC, AlexMax commented on common/p_enemy.cpp
> +	         level.mapname == "E4M8")
I'm not sure the right play is hardcoding the map name.  Is there no way to do this otherwise?

2022-01-25 03:14 UTC, AlexMax commented on common/p_enemy.cpp
> +	         level.mapname == "E4M8")
Nevermind, I see what's going on.  How big of a pain in the neck would it be to add support for the following MAPINFO tokens?

- SpecialAction_ExitLevel
- SpecialAction_OpenDoor
- SpecialAction_LowerFloor
- SpecialAction_KillMonsters 

Seems like it just be a couple of one-note tokens that set a flag.

2022-01-27 18:26 UTC, rakohus commented
Tested on newest CI build.

D2 Map07 broken. After mancs are killed it drops the walls as lifts instead of a floor lower special. After arachs are killed, no floor stair raise

Could not load into doom.wad

2022-01-31 00:41 UTC, bcahue commented
I took a look at this PR and played DOOM2 MAP07 and found it to be working. However, loading into DOOM.WAD caused an error at MIType_SpecialAction_OpenDoor() in g_mapinfo.cpp on line 1096.

2022-01-31 01:04 UTC, bcahue commented
I did however see the same DOOM2 MAP07 behavior with the CICD artifact. Not sure what's happening there.

2022-02-01 17:06 UTC, rakohus commented
Tested doom.wad e1m8, e2m8, e3m8, e4m6, and e4m8. Tested doom2.wad map07 and map30. Everything appears to be working fine now!

2022-02-02 02:28 UTC, AlexMax approved these changes
LGTM.  Thanks for the cleanup.

2022-02-02 02:29 UTC, merged