SNDINFO Improvements
odamex/odamex pull request #617
Opened 2022-03-10 07:24 UTC by DeathEgg

Ported over a few ZDoom SNDINFO upgrades, namely $alias and $random. I also converted the menu quit to use it (but not the randomized enemy sounds for demo compatibility reasons) as a part of abstracting gameinfo so it can be serialized instead of hard coded.

2022-03-12 03:55 UTC, AlexMax commented on client/src/s_sound.cpp
> +					sprintf(mapname, "MAP%02d", os.getTokenInt());
At some point this needs to be removed.

2022-03-12 03:58 UTC, AlexMax requested changes
Please fix this one C++11-ism and you're good.

2022-03-12 03:58 UTC, AlexMax commented on common/s_sound.h
> +	int link = NO_LINK;
This is not valid C++98.

2022-03-12 04:30 UTC, DeathEgg commented on common/s_sound.h
> +	int link = NO_LINK;
Fixed in latest commit

2022-03-20 19:38 UTC, AlexMax approved these changes

2022-03-21 01:59 UTC, merged