Use constexpr when useful
odamex/odamex pull request #658
Opened 2022-04-17 01:20 UTC by DeathEgg

Change types to constexpr where it makes sense throughout Odamex

2024-08-18 05:08 UTC, fuzztooth commented
Bumping - is this still useful?

2025-01-13 08:27 UTC, electricbrass commented
Yes, this would still be useful.

2025-01-13 09:13 UTC, electricbrass requested changes
Overall this looks good. There's a couple spots where it looks like it got messed up during merges.

2025-01-13 09:13 UTC, electricbrass commented on client/src/c_console.cpp
> +		const int newLineCount = std::count(outline, outline + strlen(outline), '\n');
Looks like this line got messed up in a merge, should be `const int newLineCount = std::count(logStr.begin(), logStr.end(), '\n');`

2025-01-13 09:13 UTC, electricbrass commented on client/src/c_console.cpp
> +FORMAT_PRINTF(1, 2) int STACK_ARGS Printf(const char* format, ...)
These FORMAT_PRINTF functions no longer exist in protobreak, looks like they accidentally got brought in from stable at some point. They should be deleted.

2025-01-13 09:13 UTC, electricbrass commented on client/src/r_sky.cpp
> -
This variable still needs to be declared somewhere. Looks like an earlier commit had it declared at the point it's first used down below.

2025-01-13 09:13 UTC, electricbrass commented on client/src/d_netinfo.cpp
> +constexpr byte UserInfo::weapon_prefs_default[NUMWEAPONS] = {
Making this constexpr causes the Ubuntu 18.04 and Fedora builds to fail.

2025-01-14 02:04 UTC, merged