Hack to make the PlayerSetup hack keep track of the menu stack.
odamex/odamex pull request #816
Opened 2022-12-16 02:36 UTC by Acts19quiz

The following is a pull request to address the issue where the "hacked" way of getting PlayerSetup to work with Odamex's menu doesn't keep track of the menu stack. Specifically, this is to address the bug where upon entering "PLAYER SETUP", exiting the menu immediately goes directly back to the game, not the previous OPTIONS menu.

This introduces a check for whether or not PSetupDef is active, and a boolean to catch differing situations from reaching PLAYER SETUP from Escape or from F4.

2022-12-16 14:58 UTC, DoomCoder commented
That is an annoying bug. We also fixed it with a different approach which is a little simpler. Here's the patch for reference:
[player-menu-fix-patch.txt](https://github.com/odamex/odamex/files/10246739/player-menu-fix-patch.txt)
The full source is in a fork here: https://github.com/DoomBattleZone/odamex/tree/doombattlezone

2022-12-16 15:49 UTC, Acts19quiz commented
I searched issues and pull requests to make well sure I wasn't doing something already done. Oh well. I guess the devs can do whatever with this.

2022-12-17 19:33 UTC, AlexMax commented
@Acts19quiz Found a bug in this version.

If you bind a key to `menu_options`, press it, and then hit escape, you will immediately exit the menu stack instead of going to the main menu.  However, if you bind a key to `menu_player` and then press it, pressing Escape will hit the Options menu, and not back you out of the menus completely.

That's the only issue I found - the normal route from Options to Player Setup seems to work just fine.

2022-12-17 19:33 UTC, AlexMax requested changes
See previous comment.

2022-12-17 20:40 UTC, Acts19quiz commented
I changed the bool to an int to catch more means of entry into the menu.

2022-12-19 01:57 UTC, AlexMax approved these changes
LGTM!  Thanks for the patch!

2022-12-19 01:57 UTC, merged