Update M_PlayerNameChanged to keep track of PSetupDepth and not immediately exit the menu.
odamex/odamex pull request #886
Opened 2023-08-10 18:01 UTC by Acts19quiz

The current fix (https://github.com/odamex/odamex/pull/816) for keeping track of the menu stack depth in Player Setup has an oversight. Any submitted changes to player names immediately exits the menu. I can't find a probable cause for this.

This hot fix adds another integer to keep track of what the current menu stack depth is, then immediately issues a "menu_player" command after a successful name change. One side effect is that the fire background behind the player sprite refreshes. However, it does do the job of staying in the Player Setup menu after name changes while keeping track of what the menu stack depth should have been.

Another minor change is with regards to the policy on sprintf. I accordingly changed the name change command over to std::string.

2024-07-26 19:32 UTC, bcahue requested changes
We'll need to debug this to figure out exactly why changes in the player menu back out completely rather than simply start the player menu every change. It's a hack I can't quite stomach.

2024-07-26 21:54 UTC, Acts19quiz commented
10-4. While a simple fix, it also doesn't really answer the question of why this happens in the first place (i.e., curing the symptom vs. the disease).

2025-01-18 08:30 UTC, electricbrass commented
This is due to the name field reusing the code for handling the savegame slots. When the name field is selected with enter, `genStringStart` is set to 1, and now in `M_Responder`, when the enter key is pressed, this case will be reached:
![image](https://github.com/user-attachments/assets/39acb050-65c0-44e0-a5f7-079d9a2bdd40)
Depending on whether `genStringEnd` was set to `M_PlayerNameChanged` or `M_DoSave`, either the game will be saved or the player's name will be updated. Either way, `M_ClearMenus()` is called, and the menu is exited.

2025-01-19 19:01 UTC, closed without merging

2025-01-19 19:01 UTC, bcahue commented
Closing this as @electricbrass 's changes provides the result intended for this PR.